### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by fizzyduck** [uala/drone-rancher-deploy#3]
Would it be possible to add a license to this project so that its usage and modification are clear?

I'd like to suggest BSD.

**Comment by Leen15** [comment]
@fabn what do you think?

**Comment by fabn** [comment]
I know MIT license and it fits our project and purposes.

**Comment by fizzyduck** [comment]
MIT sounds good to me.

**Comment by Leen15** [comment]
@fabn can you add it?
