### ISSUE TITLE
Include --cacert as Environment/Secret

### ISSUE THREAD

**Issue by alexismaior** [uala/drone-rancher-deploy#6]
Hey guys!

My rancher uses an internal CA (self-signed) certificate. So, when running the plugin, the output from the "rancher login" command is always "CACert of server was not accepted, unable to login".
Do you think it would be possible to include a var that reads the --cacert on "rancher login" command from the drone secrets? (or any other amazing solution)
Thank in advance for this great plugin.

**Comment by fabn** [comment]
@alexismaior would you mind to review #7 to see if it suits your needs?

**Comment by alexismaior** [comment]
Your solution fitted perfectly for me! Thanks @fabn
